/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CollectedConsentsImport } from './routes/collected-consents'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CollectedConsentsRoute = CollectedConsentsImport.update({
  id: '/collected-consents',
  path: '/collected-consents',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/collected-consents': {
      id: '/collected-consents'
      path: '/collected-consents'
      fullPath: '/collected-consents'
      preLoaderRoute: typeof CollectedConsentsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collected-consents': typeof CollectedConsentsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collected-consents': typeof CollectedConsentsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/collected-consents': typeof CollectedConsentsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collected-consents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collected-consents'
  id: '__root__' | '/' | '/collected-consents'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectedConsentsRoute: typeof CollectedConsentsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectedConsentsRoute: CollectedConsentsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/collected-consents"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/collected-consents": {
      "filePath": "collected-consents.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
